<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DuetDiagram.Render\DuetDiagram.Render.csproj" />
    <ProjectReference Include="..\DuetDiagram.Core\DuetDiagram.Core.csproj" />
    <ProjectReference Include="..\DuetDiagram.Layout\DuetDiagram.Layout.csproj" />
  </ItemGroup>

</Project>
